/**
 * @target MZ
 * @name ItemImages
 * @plugindesc map AP item names to their sprites
 * @authors 0palite
 * @version 1.0
 * @license Unlicensed
 * @help
 *
 *
 **/

var ItemImages = ItemImages || {};

const FULL_MEAL_MAPPING = ["FoodItems", 6, 0, 0];
const RED_RING_MAPPING = ["Equipment", 2, 0, 3];
const GREEN_RING_MAPPING = ["Equipment", 2, 1, 3];
const BLUE_RING_MAPPING = ["Equipment", 2, 2, 3];
const RECRUIT_MAPPING = ["APItems2", 6, 1, 6];
const COINS_MAPPING = ["Items", 2, 1, 0];
const SINGLE_BILL_MAPPING = ["Items", 4, 0, 0];
const TWO_BILL_MAPPING = ["Items", 4, 1, 0];
const BIG_BILL_MAPPING = ["Items", 4, 2, 0];
const SINGLE_BILL_COINS_MAPPING = ["Items", 6, 0, 0];
const TWO_BILL_COINS_MAPPING = ["Items", 6, 1, 0];
const BIG_BILL_COINS_MAPPING = ["Items", 6, 2, 0];

const ITEM_NAME_IMAGE_MAPPING = {
  "Healing Spray": ["Items", 4, 1, 6],
  "Suturing Kit": ["KeyItems", 2, 1, 3],
  "Medic-in-a-jar": ["APItems", 6, 0, 0],
  "Rat Baby Thing": ["KeyItems", 6, 1, 4],
  "Eye Drops": ["Items", 4, 1, 2],
  Bandage: ["Items", 2, 0, 1],
  Tonic: ["Items", 2, 1, 1],
  "First Aid Kit": ["Items", 2, 2, 1],
  Balm: ["Items", 6, 0, 1],
  Antidote: ["Items", 4, 1, 1],
  "Smelling Salts": ["Items", 8, 0, 1],
  Disinfectant: ["Items", 6, 2, 1],
  Medication: ["Items", 4, 2, 1],
  Stimulant: ["Items", 8, 1, 1],
  Elixir: ["Items", 8, 2, 1],
  Elixer: ["Items", 8, 2, 1],
  "Anxiety Meds": ["Items", 4, 2, 2],
  "Bag of Chips": ["Items", 4, 0, 5],
  "Spicy Chips": ["Items", 4, 2, 5],
  "Onion-Os": ["Items", 4, 1, 5],
  "Cheez-Stix": ["Items", 2, 2, 5],
  "Chocky Bar": ["Items", 6, 1, 5],
  "Granola Bar": ["Items", 6, 2, 5],
  Muffin: ["Items", 2, 0, 5],
  Bocky: ["Items", 2, 1, 5],
  "Hard Candy": ["Items", 8, 0, 5], // this seems to be rare cherry candy not hard candy?
  "Mint Gum": ["Items", 8, 1, 5],
  "Gummi Bears": ["Items", 8, 2, 5],
  "Worm-Baked Pie": ["APItems", 8, 1, 0],
  "Succulent Fruit??": ["Items", 8, 0, 5],
  "Tonic+??": ["Items", 2, 1, 1],
  "Cheese Wedge": ["FoodItems", 6, 0, 4],
  "M dic#t10n": ["APItems2", 8, 2, 4],
  "Cola Can": ["Items", 2, 0, 6],
  "Lemon Drink Can": ["Items", 2, 1, 6],
  "Orange Drink Can": ["Items", 2, 2, 6],
  "Juice Box": ["Items", 4, 0, 6],
  "Cold Coffee": ["Items", 8, 2, 6],
  Coffee: ["Items", 8, 1, 6],
  Beer: ["Items", 6, 0, 6],
  Whiskey: ["Items", 6, 1, 6],
  Vodka: ["Items", 6, 2, 6],
  "Energy Drink": ["Items", 8, 0, 6],
  "Worm Juice": ["APItems2", 8, 0, 1],
  "Dangerous Brew": ["Items", 8, 2, 1],
  "Worm Perfume": ["APItems2", 2, 1, 5],
  "Rotten Leftovers": ["APItems", 6, 2, 3],
  Leftovers: ["APItems", 4, 2, 3],
  "Chicken Sandwich": ["FoodItems", 2, 0, 5],
  "Egg Salad Sandwich": ["FoodItems", 2, 0, 5],
  "Tomato Sandwich": ["FoodItems", 2, 0, 5],
  "Ham Sandwich": ["FoodItems", 2, 0, 5],
  Burrito: ["FoodItems", 2, 1, 5],
  "Fred's Hoagie": ["FoodItems", 4, 0, 5],
  "Rotten Pizza Slice": ["APItems", 2, 0, 0],
  "Stale Pizza Slice": ["APItems", 2, 1, 0],
  "Cheese Pizza Slice": ["APItems", 2, 2, 0],
  "Italian Pizza Slice": ["APItems", 2, 0, 1],
  "All-Dressed Pizza Slice": ["APItems", 2, 1, 1],
  "Pineapple Pizza Slice": ["APItems", 2, 2, 1],
  "Vegetarian Pizza Slice": ["APItems", 2, 0, 2],
  "Meat Lover's Pizza Slice": ["APItems", 2, 1, 2],
  "Chicken Pizza Slice": ["APItems", 2, 2, 2],
  "Deluxe Pizza Slice": ["APItems", 2, 0, 3],
  "Screaming Pizza Slice": ["APItems", 2, 1, 3],
  "Hot Cocoa": ["Items", 8, 1, 6],
  "Sewage Cocktail": ["APItems2", 4, 0, 1],
  "Fred's Burrito": ["FoodItems", 4, 1, 5],
  "Packed Meal": ["APItems", 4, 1, 3],
  "Fruit Slice": ["APItems", 2, 2, 3],
  "Silver Dust": ["APItems", 6, 0, 7],
  "Combat Surge": ["Items2", 2, 0, 0],
  "Invulnerable Syringe": ["Items2", 2, 1, 0],
  "Wrapped Gift": ["Items", 4, 2, 4],
  "Ammo Crate": ["Items", 4, 1, 4],
  "Super Explosive": ["Items", 6, 2, 3],
  "Fire Bomb": ["Items", 6, 2, 7],
  "Tumor Lump": ["Items", 8, 0, 3],
  "Filth Bomb": ["Items", 8, 0, 3],
  "Fingernail Bomb": ["Items", 8, 0, 3],
  "Tame Landmine": ["APItems", 6, 1, 0],
  Tranquilizer: ["Items", 2, 2, 3],
  Turpentine: ["Items", 8, 0, 3],
  "Shadow Bomb": ["Items", 8, 0, 3],
  "Acid Flask": ["Items", 8, 1, 2],
  "Gas Bomb": ["Items", 8, 2, 2],
  Explosive: ["Items", 6, 2, 3],
  "Dinner Plate": ["Items", 2, 0, 3],
  Snowball: ["APItems", 2, 2, 4],
  Bottle: ["Melee", 2, 2, 0],
  "Table Fork": ["Items", 4, 0, 3],
  "Table Knife": ["Items", 4, 1, 3],
  "Bowling Ball": ["Items", 4, 2, 3],
  "Throwing Dart": ["Items", 6, 0, 3],
  "Throwing Knife": ["Items", 4, 1, 3],
  Molotov: ["Items", 8, 0, 3],
  Grenade: ["Items", 8, 1, 3],
  Shuriken: ["Items", 8, 2, 3],
  "2x Shuriken": ["Items", 8, 2, 3],
  "Blood Clot Bomb": ["APItems2", 6, 1, 0],
  Teddy: ["KeyItems", 2, 2, 4],
  "Two-Dollar Coin": ["APItems", 8, 2, 3],
  "Dollar Coin": ["APItems", 2, 2, 7],
  "Chew Toy": ["APItems2", 2, 1, 6],
  "Mocha Latte": ["Items", 8, 1, 6],
  Honeycomb: ["APItems", 6, 1, 3],
  "Hling Spr ay": ["Items2", 6, 1, 0],
  "Worm Bomb": ["APItems2", 2, 2, 5],
  "Marc-André": ["APItems", 6, 0, 3],
  "All-Seeing 8-Ball": ["APItems", 6, 1, 1],
  "Special Candy": ["APItems", 4, 0, 3],
  "Rare Mint Candy": ["APItems", 4, 2, 1],
  "Rare Lime Candy": ["APItems", 4, 1, 1],
  "Rare Banana Candy": ["APItems", 4, 0, 1],
  "Rare Cherry Candy": ["APItems", 4, 0, 0],
  "Rare Soda Candy": ["APItems", 4, 1, 0],
  "Rare Licorice Candy": ["APItems", 4, 2, 0],
  "Hellfire Candy": ["APItems", 4, 1, 2],
  "Nectar Candy": ["APItems", 4, 2, 2],
  "Cheese Man": ["FoodItems", 6, 0, 5],
  "Cheese Boy": ["FoodItems", 6, 0, 5],
  "Pale Fluid": ["APItems2", 2, 2, 4],
  "Black Ooze": ["APItems", 8, 1, 1],
  "Caustic Brew": ["APItems2", 2, 0, 5],
  Cloth: ["Items", 8, 0, 7],
  Detonator: ["KeyItems", 4, 0, 7],
  Radio: ["APItems", 4, 0, 2],
  Reagent: ["Items2", 6, 0, 4],
  Enzyme: ["Items2", 6, 1, 4],
  Catalyst: ["Items2", 6, 2, 4],
  Vinegar: ["Items", 2, 0, 7],
  Gasoline: ["Items", 2, 1, 7],
  "D-Clogger": ["Items", 2, 2, 7],
  Klysox: ["Items", 4, 0, 7],
  Medicell: ["Items", 4, 1, 7],
  Purocare: ["Items", 4, 2, 7],
  Cleanerex: ["Items", 6, 0, 7],
  Herbicide: ["Items", 6, 1, 7],
  "Roach (Inventory Item)": ["APItems", 8, 0, 1],
  Mushroom: ["Items", 8, 2, 7],
  Soap: ["Items", 6, 0, 2],
  "2x Soap": ["Items", 6, 0, 2],
  Toothpaste: ["Items", 4, 0, 2],
  "2x Toothpaste": ["Items", 4, 0, 2],
  "Duct Tape": ["Items", 6, 1, 2],
  "2x Duct Tape": ["Items", 6, 1, 2],
  Junk: ["Items", 8, 1, 7],
  "TV Dinner": ["FoodItems", 2, 1, 4],
  "Frozen Pizza": ["FoodItems", 2, 0, 6],
  "Pizza Bites": ["FoodItems", 6, 2, 0],
  "Frozen Veggies": ["FoodItems", 2, 2, 1],
  "Frozen Fish": ["FoodItems", 8, 0, 0],
  "Instant Noodles": ["FoodItems", 4, 1, 1],
  "Stew Mix Carton": ["FoodItems", 4, 0, 1],
  "Can o' Beans": ["FoodItems", 4, 0, 1],
  Rice: ["FoodItems", 4, 0, 0],
  Potatoes: ["FoodItems", 4, 0, 0],
  "Tomato Can": ["FoodItems", 4, 1, 1],
  Bread: ["FoodItems", 2, 2, 4],
  "Raw Pork": ["Items", 4, 0, 4],
  "Raw Chicken": ["Items", 4, 0, 4],
  "Raw Beef": ["Items", 4, 0, 4],
  Eggs: ["FoodItems", 4, 1, 0],
  "Baby's Drawings": ["Valuables", 2, 0, 0],
  "Child's Drawings": ["Valuables", 2, 1, 0],
  Drawings: ["Valuables", 2, 2, 0],
  "Jewelry Box": ["Valuables", 4, 0, 0],
  "Anime Figure": ["Valuables", 4, 1, 0],
  "Spirit Board": ["Valuables", 4, 2, 0],
  "Comic Books": ["Valuables", 6, 1, 0],
  "Rare Comic Book": ["Valuables", 6, 2, 0],
  "Tarot Deck": ["Valuables", 8, 0, 0],
  "Card Deck": ["Valuables", 8, 1, 0],
  "Backgammon Set": ["Valuables", 8, 2, 0],
  "Old Chessboard": ["Valuables", 2, 0, 4],
  "Old Checkerboard": ["Valuables", 2, 0, 4],
  "Mazes & Wizards": ["Valuables", 2, 1, 4],
  "Tea Set": ["Valuables", 2, 2, 4],
  "Hockey Trophy": ["Valuables", 4, 0, 4],
  "Grandma's Urn": ["Valuables", 4, 1, 4],
  "Photo Album": ["Valuables", 4, 2, 4],
  "Old Picture": ["Valuables", 6, 0, 4],
  "Silverware Box": ["Valuables", 6, 1, 4],
  "Stamp Collection": ["Valuables", 6, 2, 4],
  "Box of Seashells": ["Valuables", 8, 0, 4],
  "Musical Box": ["Valuables", 8, 1, 5],
  "Elephant Statuette": ["Valuables", 8, 1, 4],
  "Kitsch Lamp": ["Valuables", 6, 1, 5],
  "Coin Collection": ["Valuables", 8, 2, 4],
  "Carved Beaver": ["Valuables", 2, 0, 1],
  "Taxidermy Dog": ["Valuables", 2, 1, 1],
  "Taxidermy Eagle": ["Valuables", 2, 2, 1],
  "Taxidermy Creature": ["Valuables", 4, 0, 1],
  "Taxidermy Squirrel": ["Valuables", 4, 1, 1],
  "Beer Stein": ["Valuables", 4, 2, 1],
  "Stack of Magazines": ["Valuables", 6, 0, 1],
  "Dirty Magazines": ["Valuables", 6, 1, 1],
  Handbag: ["Valuables", 6, 2, 1],
  "Old Speakers": ["Valuables", 8, 0, 1],
  "Manga Pile": ["Valuables", 8, 1, 1],
  "Old Game Console": ["Valuables", 8, 2, 1],
  "Vintage Game Console": ["Valuables", 2, 0, 5],
  "Hockey Cards": ["Valuables", 2, 1, 5],
  "Baseball Cards": ["Valuables", 2, 1, 5],
  "Old Records": ["Valuables", 4, 0, 5],
  "Old CDs": ["Valuables", 4, 1, 5],
  "GameKid Color": ["Valuables", 4, 2, 5],
  Watch: ["Equipment", 4, 1, 3],
  "Fitness Tracker": ["Equipment", 4, 1, 3],
  "Old Mail": ["KeyItems", 2, 1, 7],
  "Ice Melt Salt": ["KeyItems", 8, 1, 6],
  "Length of Rope": ["KeyItems", 8, 0, 6],
  "Sapper Charge": ["Items", 2, 1, 3],
  "Defused Mine": ["APItems", 6, 1, 0],
  "Dog Tags": ["APItems", 2, 1, 7],
  "Supply Crate": ["APItems", 2, 0, 5],
  "Painter's Key": ["KeyItems", 6, 2, 0],
  "Stained Key": ["KeyItems", 8, 1, 0],
  "Twilight Valve": ["KeyItems", 4, 1, 4],
  "Midnight Valve": ["KeyItems", 8, 0, 4],
  "Abyssal Valve": ["KeyItems", 8, 1, 4],
  "Hadal Valve": ["KeyItems", 8, 2, 4],
  "Apt. 33 Key": ["KeyItems", 6, 2, 0],
  "Apt. 43 Key": ["KeyItems", 8, 2, 0],
  "Padlock Key": ["KeyItems", 2, 0, 0],
  "Old Rusty Key": ["KeyItems", 2, 0, 0],
  "Apt. 21 Key": ["KeyItems", 2, 0, 0],
  "Basement Key": ["KeyItems", 2, 2, 0],
  "Store Key": ["KeyItems", 6, 1, 0],
  "Child Barrier Key": ["KeyItems", 2, 0, 0],
  "Janitor Key Ring": ["KeyItems", 6, 0, 0],
  "Door Knob": ["KeyItems", 2, 0, 4],
  "Army Guy Figure": ["KeyItems", 2, 1, 4],
  "Sybil's Journal": ["Items", 6, 2, 2],
  "Roof Access Key": ["KeyItems", 8, 1, 0],
  "Dark Room Key": ["KeyItems", 6, 2, 0],
  "Love Letter": ["KeyItems", 2, 0, 7],
  Stationery: ["KeyItems", 2, 1, 7],
  "Fountain Pen": ["KeyItems", 2, 2, 7],
  Batteries: ["Items", 6, 1, 1],
  "Simple Key": ["KeyItems", 2, 1, 0],
  "Sun Disc": ["KeyItems", 2, 0, 1],
  "Mercury Disc": ["KeyItems", 2, 1, 1],
  "Venus Disc": ["KeyItems", 2, 2, 1],
  "Earth Disc": ["KeyItems", 4, 0, 1],
  "Mars Disc": ["KeyItems", 4, 1, 1],
  "Jupiter Disc": ["KeyItems", 4, 2, 1],
  "Saturn Disc": ["KeyItems", 6, 0, 1],
  "Uranus Disc": ["KeyItems", 6, 1, 1],
  "Neptune Disc": ["KeyItems", 6, 2, 1],
  "Pluto Disc": ["KeyItems", 8, 0, 1],
  "Ceres Disk": ["KeyItems", 8, 0, 1],
  "Luna Disk": ["KeyItems", 6, 2, 1],
  "Void Disc": ["KeyItems", 8, 1, 1],
  "Negative Disc": ["KeyItems", 8, 2, 1],
  "Positive Disc": ["KeyItems", 8, 2, 1],
  "Guinea Pig": ["KeyItems", 4, 0, 2],
  "Blank VHS tape": ["KeyItems", 4, 1, 2],
  "Incorrect CCTV Recording": ["KeyItems", 4, 1, 2],
  "Correct CCTV Recording": ["KeyItems", 4, 1, 2],
  "Photo Paper": ["KeyItems", 2, 0, 2],
  "Exposed Paper": ["KeyItems", 2, 1, 2],
  "Correct Photograph": ["KeyItems", 2, 2, 2],
  "Canvas Carry Bag": ["KeyItems", 8, 0, 2],
  "Incorrect Painting": ["KeyItems", 8, 1, 2],
  "Correct Painting": ["KeyItems", 8, 1, 2],
  "Crumpled Manuscript": ["KeyItems", 6, 2, 2],
  "Clean Manuscript": ["KeyItems", 6, 1, 2],
  "Progressive Loose Manuscript": ["KeyItems", 2, 1, 7],
  "Clown Drawing": ["KeyItems", 2, 1, 7],
  "Metro Ticket": ["APItems", 6, 2, 0],
  Tongue: ["KeyItems", 4, 2, 5],
  Ear: ["KeyItems", 6, 2, 5],
  Tooth: ["KeyItems", 6, 0, 5],
  "Cassette Tape": ["APItems", 6, 2, 2],
  Rose: ["KeyItems", 8, 0, 5],
  "Four-Leaf Clover": ["APItems2", 8, 0, 2],
  "Torn-Off Face": ["APItems", 6, 2, 1],
  Lockpicks: ["MuttsInventory", 2, 0, 5],
  "Electronic Key": ["KeyItems", 4, 2, 0],
  "Empty Photograph": ["KeyItems", 2, 2, 2],
  "Tickle's Gift": ["APItems", 8, 2, 0],
  "Phillippe's Remains": ["APItems", 8, 1, 3],
  Trophy: ["MuttsInventory", 2, 2, 7],
  "Coffee Machine": ["MuttsInventory", 2, 1, 5],
  "Vending Machine Key": ["KeyItems", 6, 2, 0],
  "Jeanne's Laundry": ["KeyItems", 6, 1, 6],
  "Rat Tail": ["Equipment", 8, 0, 7],
  NeoDuo: ["KeyItems", 8, 1, 5],
  "Eugene's Key": ["KeyItems", 6, 2, 0],
  "Shrunken Head": ["KeyItems", 8, 2, 6],
  "Plumbing Tools": ["APItems", 4, 0, 6],
  "Potting Soil": ["KeyItems", 4, 1, 6],
  "Worm Egg": ["APItems", 8, 0, 3],
  "Antoine's Key": ["APItems", 8, 2, 1],
  "Jasper's Key": ["APItems", 8, 2, 1],
  "Apt. 35 Key": ["KeyItems", 8, 2, 0],
  "Telescope Pieces": ["KeyItems", 4, 2, 6],
  Telescope: ["APItems", 8, 0, 2],
  "Small Red Key": ["APItems", 8, 0, 0],
  Phone: ["KeyItems", 4, 0, 6],
  "Last Will": ["KeyItems", 8, 2, 2],
  "Old Tape": ["KeyItems", 8, 0, 3],
  "Old Photograph": ["KeyItems", 8, 1, 3],
  "Wrapped Painting": ["KeyItems", 8, 2, 3],
  "Iris Key": ["Items2", 2, 1, 1],
  Rebreather: ["Items2", 8, 0, 4],
  "Cooking Book": ["APItems2", 6, 2, 4],
  "Clyde's Key": ["APItems", 8, 2, 1],
  "Jennifer's Key": ["APItems", 8, 2, 1],
  "Auguste's Key": ["APItems", 8, 2, 1],
  "Wake the Blood Knight": ["GameCarts", 2, 0, 0],
  "Wizards Hell: Arcane Tears": ["GameCarts", 2, 1, 0],
  "Super Jumplad": ["GameCarts", 2, 2, 0],
  "Super Jumplad 2": ["GameCarts", 2, 2, 0],
  "Super Jumplad 3": ["GameCarts", 4, 0, 0],
  Catafalque: ["GameCarts", 4, 1, 0],
  "Honko's Grand Journey": ["GameCarts", 4, 2, 0],
  "Madwheels 97": ["GameCarts", 2, 0, 1],
  Wraithscourge: ["GameCarts", 2, 1, 1],
  "Massacre Princess": ["GameCarts", 2, 2, 1],
  "Kill to Shoot": ["GameCarts", 4, 0, 1],
  Myrmidon: ["GameCarts", 4, 1, 1],
  "Myrmidon XII": ["GameCarts", 4, 2, 1],
  Screamatorium: ["GameCarts", 2, 0, 2],
  "Frogit About It": ["GameCarts", 2, 1, 2],
  "Blood Ghoul Orgy 3": ["GameCarts", 2, 2, 2],
  Octocook: ["GameCarts", 4, 0, 2],
  "Space Truckerz": ["GameCarts", 4, 0, 2],
  "Reptile Football": ["GameCarts", 4, 2, 2],
  "Auntie Wilma's Crossword Challenge": ["GameCarts", 2, 0, 3],
  "Unlabeled Cartridge": ["GameCarts", 2, 1, 3],
  "Dustin Figure": ["Items2", 6, 2, 7],
  "Ratavia Figure": ["Items2", 6, 1, 7],
  "Musk Figure": ["Items2", 8, 2, 7],
  "Jacket Figure": ["Items2", 8, 0, 7],
  "Lute Figure": ["Items2", 8, 1, 7],
  "Cerulean Figure": ["Items2", 6, 0, 7],
  "green key": ["!Chara_GlitchDoor", 2, 0, 2],
  "red key": ["!Chara_GlitchDoor", 4, 0, 2],
  "yellow key": ["!Chara_GlitchDoor", 6, 0, 2],
  "blue key": ["!Chara_GlitchDoor", 8, 0, 2],
  "white key": ["!Chara_GlitchDoor", 2, 0, 6],
  "black key": ["!Chara_GlitchDoor", 4, 0, 6],
  "Scroll of Shatter": ["APItems", 8, 0, 4],
  "Scroll of Incision": ["APItems", 8, 1, 4],
  "Scroll of Impale": ["APItems", 8, 2, 4],
  "Scroll of Burn": ["APItems", 8, 0, 5],
  "Scroll of Blind": ["APItems", 8, 1, 5],
  "Scroll of Decay": ["APItems", 8, 2, 5],
  "Scroll of Heal": ["APItems", 6, 0, 4],
  "Curse of Frogs": ["APItems", 8, 0, 6],
  "Curse of Brittle Bones": ["APItems", 8, 1, 6],
  "Curse of Seizures": ["APItems", 8, 2, 6],
  "Skill: Jump Attack": ["GameCarts", 2, 2, 0],
  "Skill: Nitro Boost": ["GameCarts", 2, 0, 1],
  "Skill: Combat Medic": ["GameCarts", 4, 1, 1],
  "Skill: Screamer": ["GameCarts", 2, 0, 2],
  "Skill: Numbness": ["GameCarts", 4, 0, 0],
  "Skill: Croak Orders": ["GameCarts", 2, 1, 2],
  "Skill: Hurt Me Plenty": ["GameCarts", 2, 2, 2],
  "Skill: Octostrike": ["GameCarts", 4, 0, 2],
  "Skill: Meteor Strike": ["GameCarts", 2, 2, 1],
  "Skill: Painful Stab": ["GameCarts", 2, 1, 0],
  "Skill: Aim The Killshot": ["GameCarts", 4, 0, 1],
  "Skill: Cash Sock": ["GameCarts", 4, 2, 0],
  "Skill: Blood Madness": ["GameCarts", 2, 0, 0],
  "Skill: Long Haul Flow": ["GameCarts", 4, 0, 2],
  "Skill: Running Tackle": ["GameCarts", 4, 2, 2],
  "Skill: Dungeon Dance": ["GameCarts", 2, 1, 1],
  "Skill: Garrison": ["GameCarts", 4, 2, 1],
  "Skill: Risk Taker": ["GameCarts", 4, 1, 0],
  "Skill: Confusing Word": ["GameCarts", 2, 0, 3],
  "Skill: Tadasana": null,
  "Skill: Unleashed Beast": ["APItems", 4, 1, 7],
  "Broken Handle": ["Melee", 6, 4, 0],
  Broom: ["Melee", 2, 0, 0],
  Nightstick: ["Melee", 2, 1, 0],
  Bottle: ["Melee", 2, 2, 0],
  "Baseball Bat": ["Melee", 6, 0, 0],
  "Frying Pan": ["Melee", 6, 1, 0],
  "Golf Club": ["Melee", 6, 2, 0],
  "Folding Chair": ["Melee", 2, 0, 4],
  Candlestick: ["Melee", 2, 1, 4],
  Mop: ["Melee", 2, 2, 4],
  Hammer: ["Melee", 6, 0, 4],
  Sledgehammer: ["Melee", 6, 1, 4],
  "Metal Bat": ["Melee", 6, 2, 4],
  Mace: ["Melee", 2, 0, 1],
  "Rolling Pin": ["Melee", 2, 1, 1],
  "Ernest's Metal Bat": ["Melee", 6, 2, 4],
  "Carving Fork": ["Melee", 2, 0, 2],
  "Pool Cue": ["Melee", 2, 1, 2],
  Rake: ["Melee", 2, 2, 2],
  Dagger: ["Melee", 6, 0, 2],
  Spade: ["Melee", 6, 1, 2],
  Pitchfork: ["Melee", 6, 2, 2],
  Rapier: ["Melee", 2, 0, 6],
  Spear: ["Melee", 2, 1, 6],
  "Venom Dagger": ["MuttsInventory", 2, 0, 4],
  "Steak Knife": ["APItems2", 4, 1, 6],
  "Bread Knife": ["APItems2", 4, 2, 6],
  "Old Axe": ["Melee", 2, 2, 3],
  "Chef's Knife": ["Melee", 6, 0, 3],
  Cleaver: ["Melee", 6, 1, 3],
  "Fireman's Axe": ["Melee", 6, 2, 3],
  Claymore: ["Melee", 2, 0, 7],
  Machete: ["Melee", 2, 1, 7],
  Katana: ["Melee", 2, 2, 1],
  "Sword of Regicide": ["Melee", 2, 2, 1],
  "Combat Knife": ["Melee", 6, 0, 7],
  Scalpel: ["Melee", 6, 1, 7],
  "Kitchen Knife": ["Melee", 6, 2, 7],
  "Hellen's Cleaver": ["Melee", 6, 1, 3],
  "Greatsword?": ["Melee", 2, 0, 7],
  "Master Sword": ["Melee", 2, 0, 7],
  "Mosquito Knife": ["APItems2", 2, 0, 0],
  "Stun Baton": ["MuttsInventory", 2, 0, 3],
  Chainsaw: ["MuttsInventory", 2, 1, 6],
  "Cattle Prod Spear": ["MuttsInventory", 2, 2, 5],
  "Rat Tail Whip": ["APItems2", 6, 1, 2],
  "Rat Claws": ["APItems2", 6, 0, 3],
  "Sewage Blade": ["APItems2", 8, 1, 3],
  "Hockey Stick": ["Melee", 2, 0, 5],
  "Bone Saw": ["APItems2", 2, 0, 7],
  "Metal Detector": ["APItems2", 2, 2, 6],
  "Shadow Blade": ["APItems2", 2, 1, 7],
  "Shadow Knife": ["Melee", 2, 1, 7],
  "Misshapen Limb": ["APItems2", 6, 2, 2],
  "Patchwork Club": ["APItems2", 4, 0, 3],
  "Great Needle": ["APItems2", 8, 0, 3],
  Testsword: ["Melee", 2, 0, 7],
  "Testsword mk2": ["Melee", 2, 0, 7],
  Hellsword: ["Melee", 8, 2, 5],
  "Jawbone Club": ["APItems2", 4, 2, 2],
  "Furnace Edge": ["APItems2", 4, 1, 2],
  "Pizza Cutter": ["APItems2", 4, 1, 3],
  "Wordsmith's Hammer": ["APItems", 8, 2, 7],
  "Spear of the Word": ["APItems", 6, 2, 7],
  Spellsword: ["APItems2", 6, 0, 5],
  "Worm O' Nine Tails": ["APItems2", 6, 0, 2],
  "Stained Shears": ["APItems2", 6, 2, 3],
  "Angel's Bat": ["APItems2", 6, 1, 3],
  "Repaired Fuzzy": ["APItems", 6, 1, 5],
  "Mangled Fuzzy": ["APItems", 2, 1, 5],
  "Renegade Fuzzy": ["APItems", 2, 2, 5],
  "Worm Fuzzy": ["APItems", 2, 0, 6],
  "Gardening Shears": ["APItems2", 8, 2, 3],
  "Heirloom Greatsword": ["Melee", 2, 0, 7],
  "Demon Knuckles": ["APItems2", 6, 0, 3],
  "World Tree's Bane": ["Melee", 6, 2, 3],
  "Sky Piercer": ["Melee", 2, 1, 6],
  "Wizards' Staff": ["Melee", 2, 1, 2],
  "Rabu Hammer": ["Melee", 6, 1, 4],
  "Rotten Fang": ["Melee", 6, 0, 2],
  Voidblade: ["Items2", 8, 0, 6],
  Whisperblade: ["APItems", 4, 2, 4],
  "Snake Whip": ["Melee", 8, 0, 6],
  "Antenniform Legs": ["APItems2", 4, 2, 3],
  "Azure Greatsword": ["Melee", 8, 1, 6],
  "Right Claw": ["APItems2", 4, 2, 0],
  "Toothy Whip": ["APItems2", 2, 1, 3],
  "Tooth Knife": ["APItems2", 2, 1, 2],
  "Tooth Scimitar": ["Melee", 8, 2, 6],
  "Tooth Hammer": ["APItems2", 2, 0, 3],
  "Junk Sword": ["APItems", 8, 1, 5],
  "Me[ttal Ba2t": ["Melee", 4, 0, 5],
  "Ocular Tetherblade": ["Items2", 4, 0, 1],
  "Mossy Hammer": ["APItems2", 8, 2, 2],
  "Goblin's Claws": ["Melee", 4, 2, 6],
  "Spine Dagger": ["APItems2", 8, 2, 5],
  "Icicle Spike": ["APItems2", 4, 0, 2],
  Electroclaw: ["APItems2", 8, 2, 0],
  "Hadal Trident": ["Melee", 6, 1, 5],
  "Dual Metal Bat": ["APItems2", 2, 1, 1],
  "Dual Rapier": ["APItems2", 2, 2, 1],
  "Dual Machete": ["APItems2", 2, 0, 1],
  "Slime Spear": ["APItems2", 2, 2, 3],
  Rags: ["Equipment", 2, 0, 0],
  "Polo Shirt": ["Equipment", 2, 1, 0],
  "Button-Up Shirt": ["Equipment", 2, 2, 0],
  "T-Shirt": ["Equipment", 4, 0, 0],
  "Tank Top": ["Equipment", 4, 1, 0],
  Hoodie: ["Equipment", 4, 2, 0],
  "Christmas Sweater": ["Equipment", 6, 0, 0],
  "Denim Vest": ["Equipment", 6, 1, 0],
  "Windbreaker Jacket": ["Equipment", 6, 2, 0],
  "Leather Vest": ["Equipment", 8, 0, 0],
  "Winter Coat": ["Equipment", 8, 1, 0],
  "Trench Coat": ["Equipment", 8, 2, 0],
  "Padded Jacket": ["Equipment", 2, 0, 4],
  "Army Jacket": ["Equipment", 2, 1, 4],
  "Chest Guard": ["Equipment", 2, 2, 4],
  Hauberk: ["Equipment", 4, 0, 4],
  Breastplate: ["MuttsInventory", 2, 2, 6],
  "Flak Jacket": ["Equipment", 4, 2, 4],
  "Flock Jacket": ["Equipment", 4, 2, 4],
  "Kevlar Suit": ["Equipment", 6, 0, 4],
  "Studded Jacket": ["Equipment", 6, 1, 4],
  "Strange Robe": ["Equipment", 2, 0, 0],
  "Dark Robes": ["Equipment", 6, 2, 4],
  "Old Uniform": ["Valuables", 8, 0, 7],
  "Elegant Suit": ["Equipment", 8, 0, 4],
  "Floral Shirt": ["APItems2", 6, 0, 4],
  "Painter's Beret": ["APItems2", 4, 1, 4],
  "Giant Rat Skull": ["APItems2", 2, 1, 0],
  "Rusty Crown": ["APItems2", 2, 0, 4],
  "Gas Mask": ["Equipment", 8, 0, 2],
  Shockskull: ["APItems2", 6, 2, 0],
  Headband: ["Equipment", 2, 0, 1],
  "Wool Cap": ["Equipment", 2, 1, 1],
  "Baseball Cap": ["Equipment", 2, 2, 1],
  "Cowboy Hat": ["Equipment", 4, 0, 1],
  Colander: ["Equipment", 4, 1, 1],
  Saucepan: ["Equipment", 4, 2, 1],
  "Clown Wig and Nose": ["APItems2", 8, 0, 4],
  Trilby: ["Equipment", 6, 0, 1],
  "Top Hat": ["Equipment", 6, 1, 1],
  "Bowler Hat": ["Equipment", 6, 2, 1],
  "Bicycle Helmet": ["Equipment", 8, 0, 1],
  "Hard Hat": ["Equipment", 8, 1, 1],
  "Football Helmet": ["Equipment", 8, 2, 1],
  "Hockey Helmet": ["Equipment", 2, 0, 5],
  "Army Helmet": ["Equipment", 2, 1, 5],
  Pickelhaube: ["MuttsInventory", 2, 2, 3],
  "Motorcycle Helmet": ["Equipment", 4, 0, 5],
  "Welding Helmet": ["Equipment", 4, 1, 5],
  "Dinosaur Helmet": ["Equipment", 6, 0, 5],
  "Circlet of Reason": ["Equipment", 4, 0, 3],
  "Indigo Hockey Mask": ["Equipment", 8, 2, 5],
  Scarf: ["APItems2", 8, 0, 0],
  "Four of Spades": ["KeyItems", 6, 2, 6],
  "Rat Tail Belt": ["Equipment", 8, 0, 7],
  Glasses: ["Equipment", 2, 0, 2],
  Shades: ["Equipment", 2, 1, 2],
  Tie: ["Equipment", 2, 2, 2],
  "Training Belt": ["MuttsInventory", 2, 1, 4],
  "Comfort Belt": ["MuttsInventory", 2, 0, 6],
  "Champion's Belt": ["MuttsInventory", 2, 0, 7],
  Gloves: ["Equipment", 6, 0, 2],
  "Plastic Gloves": ["Equipment", 6, 1, 2],
  "Trauma Kit": ["MuttsInventory", 2, 1, 3],
  "Dress Shoes": ["Equipment", 8, 0, 6],
  "Running Shoes": ["Equipment", 6, 1, 6],
  "Rubber Boots": ["Equipment", 2, 0, 6],
  Clogs: ["Equipment", 2, 1, 6],
  "Winter Boots": ["Equipment", 2, 2, 6],
  "Army Boots": ["Equipment", 4, 0, 6],
  "Work Boots": ["Equipment", 4, 1, 6],
  "Cowboy Boots": ["Equipment", 6, 2, 6],
  "Vintage Sneakers": ["Equipment", 6, 0, 6],
  "High Heels": ["Equipment", 4, 2, 6],
  "Jade Earrings": ["APItems", 6, 1, 4],
  "Golden Locket": ["APItems2", 2, 2, 0],
  "Gold Ring": ["KeyItems", 2, 2, 6],
  "Ruby Ring": RED_RING_MAPPING,
  "Emerald Ring": GREEN_RING_MAPPING,
  "Sapphire Ring": BLUE_RING_MAPPING,
  "Odd Necklace": ["Equipment", 4, 0, 3],
  "Copper Bangle": ["Equipment", 4, 1, 3],
  "Silver Bracelet": ["APItems", 6, 2, 5],
  "Teeth Pendant": ["Equipment", 6, 0, 3],
  "Teef Pendant": ["Equipment", 6, 0, 3],
  "Gold Bracelet": ["APItems", 6, 1, 5],
  "Lapis Band": GREEN_RING_MAPPING,
  "Eye Amulet": ["APItems2", 6, 0, 1],
  "Ring of Alertness": BLUE_RING_MAPPING,
  "Carnelian Ring": RED_RING_MAPPING,
  "Ring of Purity": GREEN_RING_MAPPING,
  "Ring of Parity": GREEN_RING_MAPPING,
  "Asbestos Amulet": GREEN_RING_MAPPING,
  Pistol: ["Guns", 2, 0, 0],
  "Custom Handgun": ["Guns", 2, 1, 0],
  Magnum: ["Guns", 4, 0, 0],
  SMG: ["Guns", 6, 1, 0],
  "Old Rifle": ["Guns", 8, 0, 0],
  "Hunting Shotgun": ["Guns", 2, 1, 4],
  Shotgun: ["Guns", 2, 1, 4],
  "High-Caliber Rifle": ["Guns", 4, 0, 4],
  "Gatling Gun": ["Guns", 6, 0, 4],
  Flamethrower: ["Guns", 6, 0, 5],
  "Acid Sprayer": ["Guns", 6, 1, 5],
  Crossbow: ["MuttsInventory", 2, 2, 4],
  "Dart Gun": ["Guns", 2, 0, 4],
  "Grenade Launcher": ["Guns", 2, 0, 4],
  Slingshot: ["Guns", 6, 0, 6],
  "Super Slingshot": ["Guns", 6, 1, 6],
  "Shadow Gun": ["Guns", 2, 0, 0],
  "Eyeball Hat": ["APItems2", 2, 1, 4],
  "Silver Magnum": ["Guns", 4, 1, 0],
  "SMG Special": ["Guns", 6, 1, 0],
  "War Rifle": ["Guns", 8, 1, 0],
  "Babylon Typewriter": ["APItems2", 2, 2, 7],
  "X-X9 Particle Gun": ["Guns", 8, 1, 0],
  "Jaw Revolver": ["Guns", 2, 2, 4],
  "Tooth Rifle": ["Guns", 8, 2, 0],
  gun: ["Guns", 2, 1, 1],
  "Riot Shield": ["Equipment", 2, 0, 7],
  "Shroom Cap Shield": ["APItems2", 4, 2, 4],
  "Heater Shield": ["APItems2", 4, 0, 5],
  "Fungus Breastplate": ["MuttsInventory", 2, 2, 6],
  "Fungus Cap?": ["APItems2", 4, 1, 4],
  Sabatons: ["APItems2", 4, 0, 7],
  Gauntlets: ["APItems2", 4, 1, 7],
  "Broken Wing": ["APItems", 2, 0, 7],
  "Mask of Shadows": ["APItems", 4, 2, 5],
  "Midnight Suit": ["APItems", 4, 1, 5],
  "Dark Boots": ["APItems", 4, 0, 6],
  "Shadow Cloak": ["APItems", 4, 0, 5],
  "Shadow Ring": ["APItems", 6, 0, 6],
  Mittens: ["APItems", 6, 1, 4],
  "Paint-Stained Apron": ["APItems2", 4, 0, 4],
  Beret: ["APItems2", 4, 1, 4],
  "Strange Feather": ["APItems2", 4, 2, 5],
  "Paint Palette": ["APItems2", 4, 2, 7],
  "Cowardly Boots": ["APItems2", 8, 1, 4],
  "War Medal": ["Equipment", 8, 0, 3],
  "Rage Armor": ["APItems2", 8, 1, 1],
  Headphones: ["Equipment", 4, 2, 7],
  "Biting Boots": ["Equipment", 8, 1, 6],
  "Elbow Pads": ["APItems2", 4, 1, 4],
  "Crown of Fingers": ["APItems", 6, 0, 5],
  "Coat of Arms": ["APItems", 6, 2, 4],
  "Filthy Ring": GREEN_RING_MAPPING,
  "Martin's Ring": ["KeyItems", 2, 2, 6],
  "Vampiric Jacket": ["APItems2", 4, 1, 0],
  "Blood Cap": ["APItems2", 4, 0, 0],
  "Crimson Ring": ["APItems2", 6, 0, 0],
  "Mycelium Cloak": ["APItems2", 4, 1, 5],
  "Beating Heart": ["APItems", 6, 0, 2],
  "Tome of Words": ["APItems", 4, 2, 7],
  "Patchwork Hat": ["Equipment", 8, 1, 7],
  "Patchwork Jacket": ["Equipment", 8, 2, 7],
  "Patchwork Boots": ["Equipment", 6, 1, 7],
  "Needle Gloves": ["Equipment", 6, 2, 7],
  "Laser Sight Mount": ["Guns", 4, 0, 5],
  Testarmor: ["MuttsInventory", 2, 2, 6],
  "Testarmor mk2": ["MuttsInventory", 2, 2, 6],
  "Papier-Maché Crown": ["APItems", 2, 0, 4],
  "Paper-Maché Crown": ["APItems", 2, 0, 4],
  "Official Sash": ["APItems", 2, 1, 4],
  "Fred Ring": ["APItems2", 8, 1, 0],
  Straitjacket: ["Equipment", 8, 2, 6],
  "Ring of Torment": BLUE_RING_MAPPING,
  "Scarlet Scarf": ["APItems2", 4, 1, 1],
  "Yanma Belt": ["APItems2", 6, 1, 1],
  "Wormskin Robe": ["APItems2", 4, 2, 1],
  "Worm Crown": ["APItems2", 6, 2, 1],
  "Shark Tooth Amulet": ["APItems", 6, 2, 5],
  "Sea Cucumber Loafers": ["APItems2", 6, 0, 6],
  "Chrome Finish": ["APItems", 6, 1, 2],
  "Chobham Armor": ["APItems", 8, 1, 2],
  "Demon Plating": ["APItems", 2, 1, 6],
  "Fungus Fibers": ["APItems", 4, 1, 6],
  "Rhinoceros Hide": ["APItems", 2, 2, 6],
  "Tank Tracks": ["APItems", 4, 2, 6],
  "Tank Gun": ["APItems", 6, 1, 6],
  "Quad Wheels": ["APItems", 4, 2, 6],
  "Spiked Bumper": ["APItems", 4, 2, 6],
  "Cooler Unit": ["APItems", 8, 1, 2],
  "Coffee Unit": ["APItems", 8, 1, 2],
  Carbonator: ["APItems", 8, 1, 2],
  "Overdrive Chip": ["APItems", 6, 2, 6],
  "Jousting Lance": ["APItems2", 8, 1, 2],
  "Cope Cage": ["APItems", 8, 2, 2],
  "Dragon Head": ["Equipment", 6, 0, 5],
  "Dragon Body": ["APItems", 6, 1, 7],
  "Dragon Feet": ["APItems", 8, 1, 7],
  "Dragon Tail": ["APItems", 4, 0, 7],
  "Dragon Claw": ["APItems", 8, 0, 7],
  "Vnage ucky tieakeRs": ["Items2", 8, 1, 0],
  RmyJcket: ["Items2", 2, 1, 4],
  Ftblhelmt: ["Items2", 4, 1, 4],
  "Slime Boots": ["APItems2", 2, 0, 6],
  Aster: RECRUIT_MAPPING, // burnt kotd figure; looks like a silhouette
  Audrey: RECRUIT_MAPPING,
  Joel: RECRUIT_MAPPING,
  Leigh: RECRUIT_MAPPING,
  Lyle: RECRUIT_MAPPING,
  "Xaria and Montgomery": RECRUIT_MAPPING,
  Morton: RECRUIT_MAPPING,
  "Progressive Rat Child": RECRUIT_MAPPING,
  Spider: RECRUIT_MAPPING,
  Hellen: RECRUIT_MAPPING,
  Dan: RECRUIT_MAPPING,
  Ernest: RECRUIT_MAPPING,
  Roaches: RECRUIT_MAPPING,
  Sophie: RECRUIT_MAPPING,
  Phillippe: RECRUIT_MAPPING,
  Papineau: RECRUIT_MAPPING,
  "Masked Shadow Roommate": RECRUIT_MAPPING,
  "Wriggly Fred Roommate": RECRUIT_MAPPING,
  "Jasper Roommate": RECRUIT_MAPPING,
  "Player's Left Arm": ["APItems", 4, 0, 4],
  "Player's Right Arm": ["APItems", 4, 1, 4],
  "Crafting Kit": ["!SmallFurniture", 4, 0, 0],
  "Book of Crossword Puzzles": ["CookeryItems", 8, 2, 0],
  "Elevator Activation": null,
  "Sewer Grates Lowered": null,
  AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMBROS: ["APItems", 6, 0, 1],
  "Glitch Elixir x99": ["APItems2", 8, 0, 5],
  "Sam's Life Savings": SINGLE_BILL_COINS_MAPPING,
  "Taxidermy's Spare Cash": TWO_BILL_COINS_MAPPING,
  "Edwin's Spare Cash": TWO_BILL_COINS_MAPPING,
  "Frozen Apartment Spare Cash 1": TWO_BILL_COINS_MAPPING,
  "Frozen Apartment Spare Cash 2": TWO_BILL_COINS_MAPPING,
  "Wounded Neighbor's Spare Change": COINS_MAPPING,
  "Vincent's Spare Cash": SINGLE_BILL_COINS_MAPPING,
  "Louis' Spare Cash": SINGLE_BILL_COINS_MAPPING,
  "Jeanne's Spare Cash 1": SINGLE_BILL_COINS_MAPPING,
  "Jeanne's Spare Cash 2": SINGLE_BILL_COINS_MAPPING,
  "Harriet's Spare Cash": TWO_BILL_COINS_MAPPING,
  "Toxic Fred's Spare Cash": ["Items", 2, 0, 4], // "a rolled up wad of cash"
  "Hellen's Spare Cash": TWO_BILL_COINS_MAPPING,
  "3x Quarters": COINS_MAPPING,
  "3x Dollar Coins": COINS_MAPPING,
  "Ten Dollars": SINGLE_BILL_MAPPING,
  "Five Dollars": SINGLE_BILL_MAPPING,
  "Fifty Dollars": TWO_BILL_MAPPING,
  "One Hundred Dollars": TWO_BILL_MAPPING,
  "Two Hundred Dollars": BIG_BILL_MAPPING,
  "Two Hundred and Fifty Dollars": BIG_BILL_MAPPING,
  "20x Marbles": ["Guns", 6, 2, 3],
  "10x Marbles": ["Guns", 6, 2, 3],
  "Rare Marbles": ["Guns", 6, 2, 3],
  "3x Pistol Bullets": ["Guns", 2, 0, 3],
  "5x Pistol Bullets": ["Guns", 2, 0, 3],
  "10x Pistol Bullets": ["Guns", 2, 0, 3],
  "3x Rifle Bullets": ["Guns", 2, 2, 3],
  "5x Rifle Bullets": ["Guns", 2, 2, 3],
  "10x Rifle Bullets": ["Guns", 2, 2, 3],
  "3x SMG Bullets": ["Guns", 2, 1, 3],
  "5x SMG Bullets": ["Guns", 2, 1, 3],
  "10x SMG Bullets": ["Guns", 2, 1, 3],
  "3x Magnum Bullets": ["Guns", 6, 1, 3],
  "5x Magnum Bullets": ["Guns", 6, 1, 3],
  "10x Magnum Bullets": ["Guns", 6, 1, 3],
  "3x Shotgun Shells": ["Guns", 4, 0, 3],
  "5x Shotgun Shells": ["Guns", 4, 1, 3],
  "10x Shotgun Shells": ["Guns", 4, 1, 3],
  "Apt. 30 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 31 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 32 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 34 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 35 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 37 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 38 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 20 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 21 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 22 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 24 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 25 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 27 Fridge Contents": FULL_MEAL_MAPPING,
  "Rat Apt. Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. 18 Fridge Contents": FULL_MEAL_MAPPING,
  "Mutt's First Fridge Contents": FULL_MEAL_MAPPING,
  "Mutt's Second Fridge Contents": FULL_MEAL_MAPPING,
  "Mutt's Third Fridge Contents": FULL_MEAL_MAPPING,
  "Landlord's Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. B1 Fridge Contents": FULL_MEAL_MAPPING,
  "Apt. B2 Fridge Contents": FULL_MEAL_MAPPING,
  "Sewer Fridge Contents": FULL_MEAL_MAPPING,
  "Junk Pile": ["Items", 8, 1, 7],
  "10x Bandages": ["Items", 2, 0, 1],
  "5x Bandages": ["Items", 2, 0, 1],
  "Revival Item Pack": ["!SmallFurniture", 4, 0, 6],
  "Medication Pack": ["!SmallFurniture", 4, 0, 6],
  "2x Tonic": ["Items", 2, 1, 1],
  "Landlord's Couch Cash": ["Items", 6, 0, 0],
  "4x Cheese": ["FoodItems", 6, 2, 4],
  "Progressive Rent Money": BIG_BILL_MAPPING,
  "2x Table Fork": ["Items", 4, 0, 3],
  "2x Table Knife": ["Items", 4, 1, 3],
  "2x Beer": ["Items", 6, 0, 6],
  "2x Whiskey": ["Items", 6, 1, 6],
  "2x Vodka": ["Items", 6, 2, 6],
  "2x Cloth": ["Items", 8, 0, 7],
};

const DEFAULT_AP_ITEM_MAPPING = ["GameCarts", 4, 0, 3];

ItemImages.getItemImage = function (apLocationName, useDefault) {
  if (useDefault) return ItemImages.buildItemImage();
  let mapping = LookOutsideAPClient.getLocationMapping(apLocationName);
  let itemName = "";
  if (mapping) {
    const { name, trapName } = mapping;
    itemName = trapName || name;
  }
  return ItemImages.buildItemImage(itemName);
};

ItemImages.buildItemImage = function (itemName) {
  let mapping = ITEM_NAME_IMAGE_MAPPING[itemName];
  if (!mapping) mapping = DEFAULT_AP_ITEM_MAPPING;
  //keep using cart until this is ready
  //const mapping = DEFAULT_AP_ITEM_MAPPING;
  const [characterName, direction, pattern, characterIndex] = mapping;
  return {
    tileId: 0,
    characterName,
    direction,
    pattern,
    characterIndex,
  };
};

ItemImages.loadCurrentMapImages = function () {
  if (MAP_OVERWORLD_ITEM_OVERRIDES[lastLoadedMapId]) {
    let sheetsLoaded = {};
    const overrides = Object.values(
      MAP_OVERWORLD_ITEM_OVERRIDES[lastLoadedMapId],
    ).map((entry) => ItemImages.getItemImage(entry[0]).characterName);

    overrides.forEach((sheetName) => {
      if (!sheetsLoaded[sheetName]) {
        sheetsLoaded[sheetName] = true;
        ImageManager.loadCharacter(sheetName);
      }
    });
  }
};

ItemImages.shouldOverrideImage = function (url) {
  return (
    url == "img/characters/GameCarts.png" ||
    url == "img/characters/APItems.png" ||
    url == "img/characters/APItems2.png" ||
    url == "img/characters/MuttsInventory.png"
  );
};
